name: Secure Pipeline Checks

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1" # Voer SAST-scan uit elke maandag om 00:00 UTC
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      # Stap 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Stap 2: CodeQL SAST scan
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # Stap 3: Dependency Check (OWASP)
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "SecurePipeline"
          path: "."
          format: "ALL"
          failOnCVSS: "7"

      # Stap 4: Secret Scanning (Gitleaks)
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "detect --source . --no-git  --exit-code=1 --verbose"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Stap 5: Fail the pipeline if any step fails
      - name: Fail pipeline on security issues
        if: failure()
        run: exit 1
